### ISSUE TITLE
"FIELD VALUE" not exported

### ISSUE THREAD

**Issue by mationai** [MeasureAuthoringTool/bonnie#1132]
The "FIELD VALUE"  (after "RESULT" field and before "REFERENCES" field) does not seem to be exported to excel.

**Comment by mayerm94** [comment]
@fuzzthink,

The field value data that you described as missing are not expected to appear in the Excel export, since the result data in the excel export only includes the result data element type, the code representing said data element and the start and stop times (if present) for said data element. The data elements that appear in the Excel export are the results of the execution of the CQL statement at the top of the relevant column within the Excel document. You can also see the results of a statement execution on the Measure Details page within Bonnie by selecting a patient and clicking the ‘Show Result’ button that is below the CQL statement that you are interested in. For more information about this functionality please see the Bonnie User Guide https://bonnie.healthit.gov/resource/Bonnie_user_guide.pdf.

Thanks,
Matt
